#!/bin/bash

gist_url='https://gist.githubusercontent.com/owainlewis/4132852/raw/7a329c14f3129a5754cb325c0804e19874fd8d1a/Example.hs'

snapshot() {
  test "$SNAPSHOT" = "1" && cat "$1" > "$2" && return 0

  diff "$1" "$2"
}

mash-run() {
  ./mash.hs "$@"
}

snapshot <(mash-run ./doc/README.md) ./script/snapshot/README.md && \
  snapshot <(cat ./doc/README.md | mash-run -) ./script/snapshot/README.md && \
  snapshot <(mash-run $gist_url) ./script/snapshot/gist.hs && \
  echo succes && exit 0 || \
  echo failure && exit 1

exit 1
