#!/bin/bash

gist_url='https://gist.githubusercontent.com/owainlewis/4132852/raw/7a329c14f3129a5754cb325c0804e19874fd8d1a/Example.hs'

./script/build

snapshot() {
  test "$SNAPSHOT" = "1" && cat "$1" > "$2" && return 0

  diff "$1" "$2"
}

mash-bin() {
  ./dist/mash "$@"
}

snapshot <(mash-bin ./doc/README.md) ./script/snapshot/README.md && \
  snapshot <(cat ./doc/README.md | mash-bin -) ./script/snapshot/README.md && \
  snapshot <(mash-bin $gist_url) ./script/snapshot/gist.hs && \
  echo succes && exit 0 || \
  echo failure && exit 1

exit 1
